# Generated by Django 5.1.2 on 2024-11-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_car_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='amount',
            new_name='price',
        ),
    ]
